prey=100
pred=50
a=1
b=0.01
c=0.5
d=0.01
T=30
t=0
tseries=c(t)
preyseries=c(prey)
predseries=c(pred)
while(t<T){
  if(prey==0){
    cat("all the preys died lol")
    break
  }
  if(pred==0){
    cat("all the preds died lol")
    break
  }
  dt=rexp(1,rate=a*prey+b*prey*pred+c*pred+d*prey*pred)
  action=sample(c("preyborn","preydeath","preddeath","predborn"),1,prob=c(a*prey,b*prey*pred,c*pred,d*prey*pred))
  if(action=="preyborn"){
    prey=prey+1
  }
  if(action=="preydeath"){
    prey=prey-1
  }
  if(action=="preddeath"){
    pred=pred-1
  }
  if(action=="predborn"){
    pred=pred+1
  }
  t=t+dt
  tseries=c(tseries,t)
  preyseries=c(preyseries,prey)
  predseries=c(predseries,pred)
}
while(t<T){
  if(prey==0&pred!=0){
    dt=rexp(1,rate=c*pred)
    pred=pred-1
    t=t+dt
    tseries=c(tseries,t)
    preyseries=c(preyseries,prey)
    predseries=c(predseries,pred)
  }
  if(prey==0&pred==0){
    dt=0.2
    t=t+dt
    tseries=c(tseries,t)
    preyseries=c(preyseries,prey)
    predseries=c(predseries,pred)
  }
  if(pred==0&prey!=0){
    dt=rexp(1,rate=a*prey)
    prey=prey+1
    t=t+dt
    tseries=c(tseries,t)
    preyseries=c(preyseries,prey)
    predseries=c(predseries,pred)
  }
}
tdata=seq(from=0,to=30,by=0.2)
preydata=c(100)
preddata=c(50)
i=1
while(i<=150){
  n=max(which(tseries<0.2*i))
  preydata=c(preydata,preyseries[n]+round(rnorm(1,mean=0,sd=10)))
  preddata=c(preddata,predseries[n]+round(rnorm(1,mean=0,sd=10)))
  i=i+1
}
par(mfrow=c(2,2))
plot(tseries,preyseries,type="l")
plot(tseries,predseries,type="l")
plot(tdata,preydata,type="l")
plot(tdata,preddata,type="l")